---
title: "CAPRI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's start by making the graph 

```{r}
G <- matrix(0, nrow = 21, ncol = 21)

G[1,2]=1
G[1,3]=1
G[1,4]=1
G[1,5]=1
G[1,6]=1
G[2,7]=1
G[2,8]=1
G[2,9]=1
G[3,8]=1
G[3,9]=1
G[3,10]=1
G[4,11]=1
G[4,12]=1
G[5,13]=1
G[5,14]=1
G[8,15]=1
G[9,16]=1
G[9,17]=1
G[10,18]=1
G[10,19]=1
G[11,20]=1
G[12,20]=1
G[13,20]=1
G[14,21]=1
G[9,15]=1
G[10,17]=1
G[11,19]=1

G_cut <- G[-1,-1]
print(G)

```


Now we bring out some code to generate synthetic data that I wrote a long time ago
```{r}
Parents <- function(graph, node)
{
  return(which(graph[node,] != 0))
}

Generate_Data <- function(graph, Vseq, theta, N, false_pos, false_neg)
{
  p <- nrow(graph)
  Synthetic_Data <- matrix(0, nrow = N, ncol = p)
  
  for(i in 1:N)
  {
    for(j in Vseq)
    {
      parents <- Parents(graph, j)
      
      if(length(parents) != 0)
      {
        if(length(which(Synthetic_Data[i, parents] != 0)) == 0)
        {
          Synthetic_Data[i, j] = 0
        }
        else
        {
          coin_flip = rbinom(1, 1, theta[j])
          if(coin_flip == 1)
          {
            Synthetic_Data[i, j] = 1
          }
          else
          {
            Synthetic_Data[i,j] = 0
          }
        }
      }
      else{
        Synthetic_Data[i,j]=rbinom(1,1,theta[j])
      }
    }
  }
  
  for(i in 1:N)
  {
    for(j in 1:p)
    {
      if(Synthetic_Data[i,j] == 1)
      {
        Synthetic_Data[i,j] = rbinom(1, 1, 1 - false_pos)
      }
      else
      {
        Synthetic_Data[i,j] = rbinom(1, 1, false_neg)
      }
    }
  }
  return(as.data.frame(Synthetic_Data))
}
```


Let's set theta
```{r}
set.seed(9882771)
theta <- runif(21, min = 0.25, max = 0.75)
```

Load the packages 
```{r}
library(OncoBN)
library(TRONCO)
library(igraph)
```

Now for the comparison 

```{r}
comparecapri <- function(N, fpr, fnr, iters) {
  troncoprec<- c(1:iters)
  troncorecall <- c(1:iters)
  caprifpr <- c(1:iters)
  caprifnr <- c(1:iters)
  dpprec <- c(1:iters)
  dprecall <- c(1:iters)
  dpfpr <- c(1:iters)
  dpfnr <- c(1:iters)
  
  troncomcc <- c(1:iters)
  dpmcc <- c(1:iters) 

  
  for(i in 1:iters) {
    
    D <- matrix(0,nrow = N, ncol = 20)
    while(min(colMeans(D)) < 0.05) {
    theta <- runif(20,min=0.25, max = 0.75)
    mydag <- randDAG(n=20, d=3, method = "er")
    mydag <- igraph.from.graphNEL(mydag)
    Vseq <- topo_sort(mydag)
  
    G <- as_adjacency_matrix(mydag)  

  
    D <- Generate_Data(t(as.matrix(G)), Vseq, theta, N, fpr, fnr)       
    }
    
    colnames(D) <- c(1:20)
    
    Dtronco <- import.genotypes(D)
    troncomodel <- tronco.capri(Dtronco, silent = TRUE)
    
    fn <- sum(troncomodel$model$capri_bic$adj.matrix$adj.matrix.fit - G  < 0)
    fp <- sum(G - troncomodel$model$capri_bic$adj.matrix$adj.matrix.fit  < 0)
    
    troncoprec[i] <- (sum(G)-fn)/((sum(G)-fn)+fp)
    troncorecall[i] <- (sum(G)-fn)/(sum(G))
    caprifpr[i] <- fp
    caprifnr[i] <- fn
    
    tp <- sum(G)-fn
    tn <- 180 - sum(G) - fp
    
    
    troncomcc[i] <- sum(troncomodel$model$capri_bic$adj.matrix$adj.matrix.fit != G)
    
    out <- fitCPN(D, model = "DBN", k = 5, epsilon = min(colMeans(D))/2, verbose = FALSE)
    graph <- make_directed_graph(out$edgelist)
    M <- as_adjacency_matrix(graph)
    wtindex <- which(rownames(M) == "WT")
    M <- M[-wtindex,-wtindex]
    perm <- order(as.integer(rownames(M)))
    M <- M[perm, perm]
    
    for(j in 1:nrow(M)) {
      for(k in 1:nrow(M)) {
        if(M[j,k]==1) {
          if(prune(D,j,k,10^{-5}) == 0) {
            M[j,k] == 0
        }
        }
      }
    }

    fn <- sum(M - G < 0)
    fp <- sum(G - M < 0)
    
    dpprec[i] <- (sum(G)-fn)/((sum(G)-fn)+fp)
    dprecall[i] <- (sum(G)-fn)/(sum(G))
    dpfpr[i] <- fp
    dpfnr[i] <- fn
    
    tp <- sum(G)-fn
    tn <- 180 - sum(G) - fp
    
    dpmcc[i] <- sum(M != G)
    
    cat(troncomcc[i], " ", dpmcc[i], "\n")
    
  }
  
  returnlist <- list()
  returnlist[[1]] <- troncomcc
  returnlist[[2]] <- dpmcc
  return(returnlist)
}
```

```{r}
filepath <- "/Users/p"
```

Now for the experiment 
```{r}
eta <- c(0.0,0.01,0.02,0.03,0.04,0.05,0.075,0.1,0.15,0.2)
library(pcalg)
set.seed(9882771)
caprimcc <-  matrix(0, nrow = 100, ncol = length(eta))
dpmcc <- matrix(0, nrow = 100, ncol = length(eta))

for(i in 1:length(eta)) {
  print(i)
  mylist <- comparecapri(N = 400, fpr = eta[i], fnr = eta[i], iters = 100)
  caprimcc[,i] <- mylist[[1]]
  dpmcc[,i] <- mylist[[2]]
}

write.csv(caprimcc, file = "/Users/phillipnicol/Desktop/local_files/data/CPN_DP_DATA/caprimccHAMMING.csv")
write.csv(dpmcc, file = "/Users/phillipnicol/Desktop/local_files/data/CPN_DP_DATA/dpmccHAMMING.csv")

```


